# Generated by Django 3.2.12 on 2022-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='survey_genre',
            field=models.JSONField(default=dict),
        ),
    ]
