# Generated by Django 3.2.12 on 2022-05-25 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reward', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_users', models.ManyToManyField(related_name='completed_challenges', to=settings.AUTH_USER_MODEL)),
                ('listed_movies', models.ManyToManyField(related_name='listed_challenges', to='movies.Movie')),
            ],
        ),
    ]
