# Generated by Django 3.2.12 on 2022-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
