# Generated by Django 3.2.12 on 2022-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
